Fix/doc 4308
exoplatform/exo-documentation pull request #120
Opened 2019-09-05 14:40 UTC by mzorai

2019-09-05 15:06 UTC, plamarque requested changes
typos and language suggestions

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +-  a table listing the events which allowed you to gain points. This table is composed by these fields:
```suggestion
-  a table listing the events which allowed you to earn points. This table is composed by these fields:
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +   -  The user avatar with whom you or he reacted
```suggestion
   -  The user involved in the interaction
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +   -  The event you or another user made and which allowed you to gain points
```suggestion
   -  The event you or another user made and which allowed you to earn points
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +   -  The set of points you earned following the previously cited event
```suggestion
   -  The amount of points you earned following the previously cited event
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +In the ``MyBadges`` view, you can see all the available badges in each domain with statuses:
```suggestion
In the ``MyBadges`` screen, you can see all the badges available in each domain with statuses:
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +-  *Enabled status*: when the badge is fully colored which means that you already earned this badge
```suggestion
-  *Acquired*: when the badge is fully colorized it means that you already earned this badge
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +-  *Disabled status*: when the badge is fully greyed which means that you did not yet earned the badge
```suggestion
-  *Not acquired*: when the badge is fully greyed, it means that you did not earn the badge yet
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +-  *Half enabled status*: When the badge is partially colored which means that your earned points in the
```suggestion
-  *in progress*: When the badge is partially colorized it means that you started earning points in the 
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +   domain of that badge are between the  minimum and the maximum points of that badge.
```suggestion
   domain of that badge, but you've not yet reached the required threshold. 
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +   For example when the score of a badge is comprised between 500 and 1200 and that your score in the domain is 700.
```suggestion
   For example, when the required score of a badge is between 500 and 1200 and that your score in the domain is 700.
```

2019-09-05 15:06 UTC, plamarque commented on docs/Gamification.rst
> +-  The badge's points area
```suggestion
-  The badge's domain
```

2019-09-12 15:51 UTC, hghorbel approved these changes

2019-09-12 15:53 UTC, hghorbel approved these changes

2019-09-12 15:58 UTC, mzorai commented
@plamarque  we need your approval to validate this PR

2019-09-12 17:36 UTC, plamarque approved these changes
LGTM

2019-09-13 08:11 UTC, merged