DOC-4321: Reorganize all sections and develop Domain
exoplatform/exo-documentation pull request #129
Opened 2019-09-27 17:24 UTC by hghorbel

2019-09-28 19:58 UTC, plamarque requested changes
proofreading with substantial rewrite to enhance fluidity.

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +Each domain had a different context and specific applications to organize all rules and badges.
```suggestion
Each domain represents a different context and specific applications to organize all rules and badges.
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +The following are the default domains that made sense in the context of the platform environment:
```suggestion
The following are the default domains that come with eXo Platform: 
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +.. note:: You can add, edit or remove domain using :ref: `Manage Domain <Manage Domain>` in Gamification Administration .
```suggestion
.. note:: You can add, edit or remove domains using :ref: `Manage Domain <Manage Domain>` in Gamification Administration .
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +Leaderboards will give you a snapshot of your gained points progress, and of other collaborators in your platform to encourage them to gain more points.
```suggestion
Leaderboards display a snapshot of how your earned points compare to other users. It's a friendly competition designed to encourage everyone to earn more points. 
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +Place in Leaderboard is determined by number of points earned by period : Week, Month or All times and filtered by selected domain.
```suggestion
The position in the leaderboard is determined by the number of points earned over the period : Week, Month or All times and filtered by selected domain.
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +In the Leaderboard, the TOP 10 of employees having higher gained points, and every employee is presented by its Full Name, avatar and gained points.
```suggestion
In the Leaderboard, the top 10 of users having earned most points, and every user is presented with their full name, profile picture and earned points.
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +An information of your rank is displayed just below the top 10, if you are not on it.
```suggestion
Your rank is displayed just below the top 10, if you are not in it. 
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +You can also load more 10 employees by clicking on Load more button just below the Leaderboard.
```suggestion
You can also load more 10 users by clicking on Load more button just below the Leaderboard.
```

2019-09-28 19:58 UTC, plamarque commented on docs/Gamification.rst
> +When you mouse over an employee in the leaderboard, a detailed pie chart is displayed next to him displaying all pourcentages of gained points based on the domain.
```suggestion
When you mouse over a user in the leaderboard, a pie chart is displayed next to him to detail all proportions of points they earned in each domain.
```

2019-09-30 08:29 UTC, hghorbel commented
Update Done.

2019-10-11 09:35 UTC, mzorai requested changes

2019-10-11 09:35 UTC, mzorai commented on docs/Gamification.rst
> +- Knowledge : Facts, informations, and skills acquired through experiences using Forum, Wiki and Documents applications.
```suggestion
- Knowledge: Facts, information, and skills acquired through experiences using Forum, Wiki and Documents applications.
```

2019-10-11 09:35 UTC, mzorai commented on docs/Gamification.rst
> +You can also load more 10 users by clicking on Load more button just below the Leaderboard.
```suggestion
You can also load 10 more users by clicking on Load more button just below the Leaderboard.
```

2019-10-11 09:46 UTC, mzorai approved these changes

2019-10-11 14:27 UTC, plamarque requested changes
More optimizations requested

2019-10-11 14:27 UTC, plamarque commented on docs/Gamification.rst
> +.. note:: You can add, edit or remove domains using :ref: `Manage Domain <Manage Domain>` in Gamification Administration .
```suggestion
.. note:: You can add, edit or remove your own domains using :ref: `Manage Domain <Manage Domain>` in Gamification Administration .
```

2019-10-11 14:27 UTC, plamarque commented on docs/Gamification.rst
> +Leaderboards display a snapshot of how your earned points compare to other users. It's a friendly competition designed to encourage everyone to earn more points.
```suggestion
Leaderboards display a snapshot of users with most points. You always see your own rank so you can compare to others in various domains. It's a friendly competition designed to encourage everyone to engage in various activities by earning points. 
```

2019-10-11 14:27 UTC, plamarque commented on docs/Gamification.rst
> +When you mouse over a user in the leaderboard, a pie chart is displayed next to him to detail all proportions of points they earned in each domain.
```suggestion
When you mouse over a user in the leaderboard, a pie chart is displayed beside with details of the distribution of points across domains. Hence you can discover what are their sweet spot domains and learn from their behaviours.
```

2019-10-11 16:11 UTC, hghorbel commented
Done.

2019-10-11 20:12 UTC, plamarque requested changes
2nd pass proofreading and suggested optimizations

2019-10-11 20:12 UTC, plamarque commented on docs/Gamification.rst
> +Leaderboards display a snapshot of users with most points. You always see your own rank so you can compare to others in various domains. It's a friendly competition designed to encourage everyone to
```suggestion
Leaderboards display a snapshot of users with most points. You always see your own rank so you can compare yourself to others in various domains. It's a friendly competition designed to encourage everyone to engage in various activities by earning points. 
```

2019-10-11 20:12 UTC, plamarque commented on docs/Gamification.rst
> +The position in the leaderboard is determined by the number of points earned over the period : Week, Month or All times and filtered by selected domain.
```suggestion
The position in the leaderboard is determined by the number of points earned over the period : Week, Month or All times and is filtered by selected domain.
```

2019-10-11 20:12 UTC, plamarque commented on docs/Gamification.rst
> +In the Leaderboard, the top 10 of users having earned most points, and every user is presented with their full name, profile picture and earned points.
```suggestion
In the Leaderboard, the top 10 users with higher scores over the period are with their full name, profile picture and point scores.
```

2019-10-11 20:12 UTC, plamarque commented on docs/Gamification.rst
> +You can also load 10 more users by clicking on Load more button just below the Leaderboard.
```suggestion
You can also navigate in the ranks by clicking on Load more button to load 10 more entries.
```

2019-10-11 20:12 UTC, plamarque commented on docs/Gamification.rst
> +When you mouse over a user in the leaderboard, a pie chart is displayed beside with details of the distribution of points across domains. Hence you can discover what are their sweet spot domains and
```suggestion
When you mouse over a user in the leaderboard, a pie chart is displayed to illustrate the distribution of points across domains. Hence you can discover what are their sweet spot domains and learn from their behaviors.
```

2019-10-13 22:08 UTC, plamarque requested changes
another pass for proofreading

2019-10-13 22:08 UTC, plamarque commented on docs/Gamification.rst
> +Domains are the categorization of all behaviors of the platform users.
```suggestion
Domains are used to categorize all behaviors of the platform users. 
```

2019-10-13 22:08 UTC, plamarque commented on docs/Gamification.rst
> +Each domain represents a different context and specific applications to organize all rules and badges.
```suggestion
Each domain contains rules and badges related to a different context and usage of specific applications.
```

2019-10-13 22:08 UTC, plamarque commented on docs/Gamification.rst
> +In the Leaderboard, the top 10 users with higher scores over the period are with their full name, profile picture and point scores.
```suggestion
In the Leaderboard, the top 10 users with the highest scores over the period are displayed with their full name, profile picture and score (points gathered).
```

2019-10-14 10:30 UTC, hghorbel commented
Changes DONE.

2019-10-14 14:21 UTC, hghorbel commented
@plamarque waiting for your approval to merge.

2019-10-14 18:59 UTC, plamarque approved these changes
LGTM

2019-10-17 15:55 UTC, merged