Reward - managing kudos - 1 screenshot missing
exoplatform/exo-documentation pull request #142
Opened 2019-10-17 14:22 UTC by samehaidi

2019-10-17 16:00 UTC, plamarque requested changes
first pass typos and simplifications

2019-10-17 16:00 UTC, plamarque commented on docs/Administration.rst
> +To access to this interface, you have to click on "Administration" menu from the top navigation, then "Reward" - "Kudos" from the drop-down menu.
```suggestion
To access to this interface, click on "Administration" menu from the top navigation, then "Reward" > "Kudos" from the drop-down menu.
```

2019-10-17 16:00 UTC, plamarque commented on docs/Administration.rst
> +You can set the number of the allocated kudos for users to use per period of time (week, month, quarter or year).
```suggestion
You can define how many kudos users can send  per period of time (week, month, quarter or year). 
```

2019-10-17 16:00 UTC, plamarque commented on docs/Administration.rst
> +You can also restrict the use of Kudos to the members of a single space. They will be allowed to send and recieve Kudos even from other space's activities. In this case, both sender and reciever must
```suggestion
You can also restrict the use of Kudos to the members of a single space. Here space membership is simply used to indicate a group permission. Authorized users will be able to send and receive kudos from any other space.
```

2019-10-17 16:00 UTC, plamarque commented on docs/Administration.rst
> +You can access to the list of the sent kudos from the tab "Kudos List" of the same interface. The information of the sender and reciever are available.
```suggestion
You can review the list of kudos received and sent from the tab "Kudos List" of the same interface. The information of the sender and receiver are available.
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +===============
@samehaidi this hould be removed. I think it's duplicatedfrom Administration.rst

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +To access to this interface, you have to click on "Administration" menu from the top navigation, then "Reward" - "Reward" from the drop-down menu.
```suggestion
To access to this interface,  click on "Administration" menu from the top navigation, then "Reward" > "Reward" from the drop-down menu.
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +|image|
image missing

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +This tab allows you to manage the reward's sending, the periodicity and how rewards will be calculated for users at the end of each period.
```suggestion
This tab lets you to manage the rewards sending, the periodicity and how rewards will be calculated for users at the end of each period.
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +You have to choose the periodicity of sending rewards. The possible values are : week, month, quarter, semester or year.
```suggestion
Choose the periodicity for sending rewards. The possible values are : week, month, quarter, semester or year.
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +The interface is divided into two blocs : a bloc to setup the rewards for recieved kudos and a bloc to setup the rewards for gamification points.
```suggestion
The interface is divided into two blocks : a block to setup the rewards for kudos and a block to setup the rewards for gamification points.
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +For each bloc you will have to specify if there is a minimal threshold to reward users. The default value is "0", which means that the users are rewarded automatically if they recieve kudos or earn a
```suggestion
For each bloc you can specify a minimal threshold to reward users. The default value is "0", which means that the users are rewarded automatically if they receive kudos or earn any gamification points.
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +You have to select the checkbox "Use pools" if you want to use the pools in the rewards calculation and this for kudos and gamification.
```suggestion
Select the checkbox "Use pools" if you want to use the pools in the rewards calculation and this for kudos and gamification.
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +You have three choices to set the reward budget for each both blocs :
```suggestion
For each case, you have three ways for controlling your rewarding budget :
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +- **By a fixed budget:** This option allows you to set a total amount of token for all users rewards. This amount will be divided between the different users. The calculation will be done according t
```suggestion
- **By a fixed budget:** This option allows you to set a total amount of tokens for all users rewards. This amount will be divided between the different users. The calculation will be done according to the chosen mode (use pools or not). 
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +- **By a fixed budget per eligible member:** This option alows you to fix a budget to be divided between the eligible members.  The calculation will be done according to the chosen mode (use or not o
```suggestion
- **By a fixed budget per eligible member:** This mode lets you set a dynamic budget sized according to the number of active (eligible) users.  The calculation will be done according to the chosen mode (use of pools or not).
```

2019-10-17 16:00 UTC, plamarque commented on managing rewards kudos ..etc
> +- **By a fixed budget per point:** This option alows you to fix a budget per point (for each recieved kudos or earned gamification points).
```suggestion
- **By a fixed budget per point:** This mode lets you define a budget per so-called "point" (for each kudos or gamification received).
```

2019-10-18 14:17 UTC, samehaidi commented on managing rewards kudos ..etc
> +===============
as explained, this file .rst is not meant to be in this PR

2019-10-18 17:11 UTC, plamarque requested changes
images missing and duplicate text to fix. Also a couple of smaller edits suggested.

2019-10-18 17:11 UTC, plamarque commented on docs/Administration.rst
> +To access to this interface, click on "Administration" menu from the top navigation, then "Reward" > "Kudos" from the drop-down menu.
```suggestion
To access this interface, click on "Administration" menu from the top navigation, then "Reward" > "Kudos" from the drop-down menu.
```

2019-10-18 17:11 UTC, plamarque commented on docs/Administration.rst
> +You can also restrict the use of Kudos to the members of a single space. Here space membership is simply used to indicate a group permission. Authorized users will be able to send and receive kudos f
```suggestion
You can also restrict the use of kudos to the members of a single space. Here, the space membership is simply used as a group permission. Authorized users will be able to send and receive kudos from any other space.
```

2019-10-27 17:50 UTC, samehaidi commented
Extra file deleted, suggestions commited

2019-10-28 12:22 UTC, plamarque approved these changes
LGTM

2019-10-28 17:24 UTC, merged