remove simple form from documentation and update screenshots (+some changes in news intro)
exoplatform/exo-documentation pull request #147
Opened 2019-11-13 15:43 UTC by samehaidi

2019-11-13 16:16 UTC, plamarque requested changes
first pass of proofreading and language suggestions

2019-11-13 16:16 UTC, plamarque commented on docs/GettingStarted.rst
> +Publishing a news allows you to easily write, broadcast  and share communication content into other spaces. You can also make it visible to all platform users by pinning articles into home page.
```suggestion
Publishing a news lets you easily write, broadcast  and share communication content into other spaces. You can also make it visible to all platform users by pinning articles on the home page.
```

2019-11-13 16:16 UTC, plamarque commented on docs/GettingStarted.rst
> +It is possible to write an article directly from a space composer. This feature is intended to improve and simplify the way information is shared. It allows contributors to create content without hav
```suggestion
It is possible to write an article directly from a space composer. This feature is intended to improve and simplify the way information is shared. Users can contribute content intuitively without any former training to the content management system. News offers an inclusive and collaborative way to manage communication.
```

2019-11-13 16:16 UTC, plamarque commented on docs/GettingStarted.rst
> +To post an article, click "write an article" located at the buttom of the space's composer.
```suggestion
To post a news article, click "write an article" located at the bottom of the space's composer. 
```

2019-11-13 16:16 UTC, plamarque commented on docs/GettingStarted.rst
> +Write or paste in your article. Add a title, summary, image, and content as desired, then press the "Post" button in the top-right corner of the screen.
```suggestion
Write or paste your article content in. Choose a title, a summary and an illustrative image as desired, then press the "Post" button in the top-right corner of the screen. 
```

2019-11-13 16:30 UTC, thomasdelhomenie requested changes

2019-11-13 16:30 UTC, thomasdelhomenie commented on docs/GettingStarted.rst
> -.. |image174| image:: images/sharenews/saved_shortform.png
These images files must be removed.

2019-11-13 18:08 UTC, samehaidi commented on docs/GettingStarted.rst
> -.. |image174| image:: images/sharenews/saved_shortform.png
done

2019-11-13 23:39 UTC, plamarque approved these changes
LGTM

2019-11-14 07:32 UTC, thomasdelhomenie approved these changes

2019-11-14 08:58 UTC, merged