DOC-4359: Update remote edit documentation with details for linux OS
exoplatform/exo-documentation pull request #193
Opened 2020-01-29 14:35 UTC by mzorai

2020-02-06 09:57 UTC, ahamdi requested changes

2020-02-06 09:57 UTC, ahamdi commented on docs/Manage-Documents.rst
> +		  Java Applet enabled. This is required for opening Non-MS Office
I am not sure if this is still required

2020-02-06 10:10 UTC, mzorai commented on docs/Manage-Documents.rst
> +		  Java Applet enabled. This is required for opening Non-MS Office
OK, should I remove this note then?

2020-02-06 10:24 UTC, ahamdi commented on docs/Manage-Documents.rst
> +		  Java Applet enabled. This is required for opening Non-MS Office
@hassenelkamel-exo Could you confirm please?

2020-02-07 14:55 UTC, hassenelkamel-exo commented on docs/Manage-Documents.rst
> +		  Java Applet enabled. This is required for opening Non-MS Office
I m agree with you, java applet is not required

2020-02-07 14:57 UTC, mzorai commented on docs/Manage-Documents.rst
> +		  Java Applet enabled. This is required for opening Non-MS Office
OK so I remove this note from documentation

2020-02-11 09:35 UTC, hassenelkamel-exo approved these changes

2020-02-11 15:37 UTC, ahamdi approved these changes

2020-02-11 15:52 UTC, merged