Fix/5.3/update info version
exoplatform/exo-documentation pull request #197
Opened 2020-02-07 09:14 UTC by samehaidi

2020-02-07 16:20 UTC, plamarque requested changes
changes suggested

2020-02-07 16:20 UTC, plamarque commented on docs/GettingStarted.rst
> +.. warning:: News feature is beta on 5.3 version. It will be released officially on 6.0 Version. However it is still possible to install the addon and use it in the current version.
```suggestion
.. warning:: News feature is beta on eXo Platform 5.3. It's planned to be released as generally available in eXo Platform 6.0 Version. It is not pre-packaged in eXo Platform 5.3, however it is still possible to install the addon in order to preview the feature..
```

2020-02-07 16:21 UTC, plamarque requested changes
IMO you should also add a similar warning on What's new page

2020-02-07 16:23 UTC, mzorai commented
> IMO you should also add a similar warning on What's new page
Sorry for dipping in but just as info I didn't add News feature on what's new page I planned to do it when it is released

2020-02-07 19:11 UTC, plamarque commented
> > IMO you should also add a similar warning on What's new page
> 
> Sorry for dipping in but just as info I didn't add News feature on what's new page I planned to do it when it is released

 I assumed it was already there. It's fine then.

2020-02-13 07:22 UTC, plamarque approved these changes

2020-02-13 08:45 UTC, merged