DOC-4382: Update screebshots for Allow to add spaces with dynamic layout
exoplatform/exo-documentation pull request #214
Opened 2020-04-01 11:26 UTC by hghorbel

2020-04-01 11:43 UTC, boubaker commented on docs/Administration.rst
> +|                        | or not.                                           |
```suggestion
| Use dynamic layout     | When enabled, the group (can be a space) site layout |
|                        | will be retrieved from current PORTAL site layout. |
|                        | This options will be turned off automatically if the user edits the group site |
|                        | layout and saves changes. To turn it on again, you should edit the group site |
|                        | properties then enable the checkbox and save changes. |
```

2020-04-01 16:04 UTC, plamarque requested changes
just a small typo. Otherwise OK.

2020-04-01 16:04 UTC, plamarque commented on docs/Administration.rst
> +s
```suggestion

```

2020-04-01 16:53 UTC, hghorbel commented
Typo problem resolved.

2020-04-02 16:30 UTC, plamarque approved these changes
LGTM

2020-04-02 16:56 UTC, merged