DOC-4381: Add defintions for platform groups
exoplatform/exo-documentation pull request #218
Opened 2020-04-02 19:10 UTC by mzorai

2020-04-03 15:09 UTC, plamarque submitted a review, later dismissed

2020-04-03 15:09 UTC, plamarque commented on docs/Administration.rst
> +**Organization** helps you to organize your company members: Employees, managers...
deparments, teams or any way to represent your organization

2020-04-03 15:09 UTC, plamarque commented on docs/Administration.rst
> +**Organization** helps you to organize your company members: Employees, managers...
also indicate that these groups have no special effects in the product. they are just here as placeholder

2020-04-03 15:09 UTC, plamarque commented on docs/Administration.rst
> +.. note: Any registred user is autolatically added to the platform/users group to be able to connect.
automatically

2020-04-03 15:09 UTC, plamarque commented on docs/Administration.rst
> +.. note: Any registred user is autolatically added to the platform/users group to be able to connect.
didnt you forget web contributors?

2020-04-03 15:33 UTC, mzorai commented on docs/Administration.rst
> +**Organization** helps you to organize your company members: Employees, managers...
OK, thanks for the tip

2020-04-03 15:34 UTC, mzorai commented on docs/Administration.rst
> +.. note: Any registred user is autolatically added to the platform/users group to be able to connect.
yes, it is coming with the next commit

2020-04-03 19:45 UTC, cmagral commented on docs/Administration.rst
> +The membeship, such as `manager:/platform/users`, is defined by both membership type (manager, member, author...)
Typo here.

2020-04-06 09:41 UTC, mzorai commented on docs/Administration.rst
> +The membeship, such as `manager:/platform/users`, is defined by both membership type (manager, member, author...)
OK

2020-04-07 10:48 UTC, ahamdi requested changes

2020-04-07 10:48 UTC, ahamdi commented on docs/Administration.rst
> +- `*` defines the whole roles
```suggestion
- `*` all the roles combined, that means a user with * membership type will have the permissions assigned to all  membership types within this group
```

2020-04-07 13:37 UTC, ahamdi approved these changes
LGTM

2020-04-08 13:02 UTC, merged