DOC-4389: Add legacy social intranet, the stream and widgets in the D…
exoplatform/exo-documentation pull request #227
Opened 2020-04-16 18:27 UTC by hghorbel

…W documentation

2020-04-16 19:35 UTC, plamarque requested changes
please change images with more meaningfull usernames than abcde199

2020-04-16 19:57 UTC, plamarque requested changes
reviewed text and suggested many language changes.
Generally speaking avoid using future tense for describing interfaces. Present is better.

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +This section introduces you to the navigation in the Digital Workplace, ie **Snapshot**. Besides,
```suggestion
This section introduces the navigation in the Digital Workplace site. Besides,
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> + * :ref:`Digital Workplace applications <DW-Gadgets>`
```suggestion
 * :ref:`Digital Workplace widgets <DW-Gadgets>`
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +   Introduction to applications that come with the Digital Workplace.
```suggestion
   Introduction to widget blocks that come with the Digital Workplace.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +Digital Workplace applications
```suggestion
Digital Workplace widgets
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +Digital Workplace applications are ones which come with the Digital Workplace, including:
```suggestion
Digital Workplace widgets come with the Digital Workplace, including:
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +When all the actions are performed, you will can remove this application from the Stream Page by clicking
```suggestion
When all the actions are performed, you can remove this widget from the Stream Page by clicking
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +Close on the application header|DW-2|.
```suggestion
Close on the header|DW-2|.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +    .. note:: - You cannot get the Getting Started application back when it is removed.
```suggestion
    .. note:: - You can’t get the Getting Started widget back when it is removed.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +The welcome back widget is an application that welcomes you with some information about your spaces, connections,
```suggestion
The welcome back widget is an block that welcomes you with some information about your spaces, connections, 
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +your points obtained in the current week and your weekly rank.
rank is probably not clear at this stage to a new comer. We should link to the section in gamification where rank concept is described.

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +- For your spaces, you will see the total number of spaces that you're member of, or created.
```suggestion
- For your spaces, you will see the total number of spaces that you're member of.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +  If you have some requests to join a space, you will find a badge displaying the number of requests
```suggestion
  If you have some invitations to join spaces, you will find a badge displaying the number of awaiting invitations
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +  you have and you can just click on them to display them in a drawer.
```suggestion
  you have and you can just click on it to display them in a drawer.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +- You will have your Weekly gamifications gained points and by clicking on your points, you will have a pie chart
```suggestion
- You can see the points you earned his week and by clicking on your points, you will have a pie chart 
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +  that presents your points partition by domains.
```suggestion
  that presents your points distribution by domain.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +- You will have also your Weekly rank and by clicking on your rank, you will have a leaderboad
```suggestion
- You can also your rank for this week and by clicking on your rank, you can see a leaderboard 
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +  that presents your position comparing to you collaborators and your weekly gained points.
```suggestion
  that presents your position comparing to other members and the amount of points you earned this week so far.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +The My Orders widget will presents to you the number of your current orders in the Perkstore.
```suggestion
The Perks Store widget will presents to you the number of your current orders in the Perkstore.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +Perkstore
Perks Store

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +By clicking on this number, the Perkstore page will be opened on the list of all your orders.
```suggestion
By clicking on this number, the Perks Store application will be opened on the list of all your orders.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +The Wallet widget will presents to you the number of your cauris on your wallet.
```suggestion
The Wallet widget displays the number of your balance of your wallet.
```

2020-04-16 19:57 UTC, plamarque commented on docs/GettingStarted.rst
> +Cauris are earned by the points you gained on gamification when you react and collabore with your collaborators.
```suggestion
You will receive tokens regularly in your wallet by collaborating through the digital workplace apps. 
```
Should link to the section of the doc that talks about rewards in wallet

2020-04-16 21:46 UTC, plamarque commented on docs/GettingStarted.rst
> +       applications, Spaces and Settings.
```suggestion
       widgets, spaces and settings.
```

2020-04-16 21:48 UTC, plamarque commented on docs/GettingStarted.rst
> +   Introduction to the Digital Workplace Homepage.
```suggestion
   Introduction to the Snapshot page, all your Digital Workplace at a glance .
```

2020-04-16 22:18 UTC, plamarque requested changes
proofreading pass #2 to fix some typos inteoduced by pass #1 and suggest more language simplifications

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +.. _DW-Gadgets:
Widgets

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +Digital Workplace widgets come with the Digital Workplace, including:
```suggestion
Digital Workplace comes with several widget applications preinstalled on default pages to provide useful info and handy shortcuts to all apps and key information such as :
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +When all the actions are performed, you can remove this widget from the Stream Page by clicking
```suggestion
When all the actions are performed, you can dismiss this widget permanently by clicking
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +    .. note:: - You can’t get the Getting Started widget back when it is removed.
```suggestion
    .. note:: - You can’t get the Getting Started widget back after you closed it.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +your points obtained in the current week and your weekly rank.
```suggestion
the points you earned and the rank you reached this week.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +The Perks Store widget will presents to you the number of your current orders in the Perkstore.
```suggestion
The Perks Store widget displays pending orders you have in the Perks Store application.
```

should add a link to Pers Store doculentztion section

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +The Wallet widget displays the number of your balance of your wallet.
```suggestion
The Wallet widget displays the token balance of your wallet.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +You will receive tokens regularly in your wallet by collaborating through the digital workplace apps.
add a see Rewards (link to Reward sextion in the doc)

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +- You will see your avatar and your name just after the welcome Back label.
```suggestion
- You can see your profile picture and your name just after the welcome Back label.
```

I hate the term avatar
turn this sentence to present tense. Future makes no sense when describing an interface.

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +- For your spaces, you will see the total number of spaces that you're member of.
```suggestion
- The widget also displays the  total number of spaces that you're member of.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +  If you have some invitations to join spaces, you will find a badge displaying the number of awaiting invitations
```suggestion
  A counter of your pending space invitations is displayed in a small badge
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +  you have and you can just click on it to display them in a drawer.
```suggestion
  Click the badge to display all invitations and easily accept or refuse them.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +    .. note:: - If you don't have any request to join a space, the badge will be hidden.
```suggestion
    .. note:: - When you don't have any space invitation, the badge is hidden.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +- For your connections, you will see the total number of connections on your network.
```suggestion
- this widget also reminds you the size of your social network by displaying your current number of Connections.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +  If you have some connection requests, you will find a badge displaying the number of requests
```suggestion
  When you have some pending  connection requests, a small badge displays a requests counter.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +  you have and you can just click on them to display them in a drawer.
```suggestion
 Click the badge to display the list of pending requests and accept or refuse them.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +    .. note:: - If you don't have any request to join a space, the badge will be hidden.
```suggestion
    .. note:: - When you don’t have any connection request, the badge is hidden.
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +- You can see the points you earned his week and by clicking on your points, you will have a pie chart
```suggestion
- You can see the points you earned this week and by clicking on your points, you can see a pie chart 
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +- You can also your rank for this week and by clicking on your rank, you can see a leaderboard
```suggestion
- You can also see your rank for this week and by clicking on your rank, you can see a leaderboard 
```

2020-04-16 22:18 UTC, plamarque commented on docs/GettingStarted.rst
> +  that presents your position comparing to other members and the amount of points you earned this week so far.
```suggestion
  that presents your position comparing to other members and how many points you earned this week so far.
```

2020-04-17 11:31 UTC, hghorbel commented on docs/GettingStarted.rst
> +You will receive tokens regularly in your wallet by collaborating through the digital workplace apps.
Done.

2020-04-17 11:48 UTC, hghorbel commented on docs/GettingStarted.rst
> +The Perks Store widget will presents to you the number of your current orders in the Perkstore.
We don't have documentation for perks store, all what i find is a link to github page for Perks sotre.

2020-04-17 11:56 UTC, hghorbel commented on docs/GettingStarted.rst
> +your points obtained in the current week and your weekly rank.
Done.

2020-04-17 12:42 UTC, hghorbel commented
@plamarque changes done

2020-04-17 19:24 UTC, plamarque approved these changes
LGTM

2020-04-18 14:51 UTC, merged