Document the new UX and UI for space member application
exoplatform/exo-documentation pull request #249
Opened 2020-05-28 10:51 UTC by hghorbel

2020-05-28 13:22 UTC, plamarque requested changes

2020-05-28 13:22 UTC, plamarque commented on docs/Manage-Space.rst
> +After :ref:`creating a space <Create-Space>`, by default it has the default banner (related to the space template) and the default space's icon.
```suggestion
After :ref:`creating a space <Create-Space>`, it has the default banner (related to the space template) space icon. 
```

2020-05-28 13:22 UTC, plamarque commented on docs/Manage-Space.rst
> +Contrary to the banner, you can choose an another space avatar only in your space **Settings**.
```suggestion
Unlike the banner, you can choose another space avatar only from space **Settings**.
```

2020-05-28 13:22 UTC, plamarque commented on docs/Manage-Space.rst
> +-  The same actions icons we already have in the platform default topbar:
```suggestion
-  The usual icons of the topbar: 
```

2020-05-28 13:22 UTC, plamarque commented on docs/Manage-Space.rst
> +In mobile devices, applications navigation bar is displayed on the bottom and scrollable right and
```suggestion
On mobile devices, application navigation bar is displayed at the bottom and can be scrolled from right to
```

2020-05-28 13:22 UTC, plamarque commented on docs/Manage-Space.rst
> +You can display the list of invited members just by selecting **Invited** on the filter space members pulldown.
```suggestion
You can display the list of invited users just by selecting **Invited** on the filter space members pulldown.
```

users become members only after they are accepted. so invited members does not exist. it's invited users.

2020-05-28 13:22 UTC, plamarque commented on docs/Manage-Space.rst
> +Display Requestd to join  members
```suggestion
Display Requested to join  members
```

2020-05-28 13:22 UTC, plamarque commented on docs/Manage-Space.rst
> +Every changement is automatically saved and the new applications order is available after a refresh.
```suggestion
Every change is automatically saved and the new applications order is available after a refresh.
```

2020-06-02 10:15 UTC, hghorbel commented
@plamarque waiting for your review.

2020-08-24 15:44 UTC, plamarque requested changes
typos and small languages fixes suggested

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +When scrolling down in the space's activity stream, or applications, you always have the space' avatar, the space name and their applications in the topbar.
```suggestion
When scrolling down in the space's activity stream, or applications, you always have the space's avatar, the space name and their applications in the topbar.
```

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +   -  Predefined Apps : Home, Documents, Tasks, Forum, Wiki, Calendar, Members, Settings
Wiki was renamed Notes

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +   -  Predefined Apps : Home, Tasks, Documents, Calendar, Wiki, Forum, Members, Settings
```suggestion
   -  Predefined Apps : Home, Tasks, Documents, Calendar, Notes, Forum, Members, Settings
```

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +   -  Predefined Apps : Home, Calendar, Documents, Wiki, Tasks, Members, Settings
```suggestion
   -  Predefined Apps : Home, Calendar, Documents, Notes, Tasks, Members, Settings
```

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +   -  Predefined Apps : Home, Documents, Tasks, Forum, Wiki, Calendar, Members, Settings
```suggestion
   -  Predefined Apps : Home, Documents, Tasks, Forum, Notes, Calendar, Members, Settings
```

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +          just by clicking on Edit --> Page --> Edit layout and then drag and drop the portelt you want to add.
```suggestion
          just by clicking on Edit --> Page --> Edit layout and then drag and drop the app you want to add.    
```

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +By clicking on the edit icon in front of the General label, uyou can change space's information like:
```suggestion
By clicking on the edit icon in front of the General label, you can change space's information like: 
```

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +-  To promote a member to the manager position, click **Promote Manager** in the
```suggestion
-  To grant a member the space's manager role, click **Promote Manager** in the
```

2020-08-24 15:44 UTC, plamarque commented on docs/Manage-Space.rst
> +:ref:`Go to the Spaces page <Access-Space>` and you will see all your spaces and ones
```suggestion
:ref:`Go to the Spaces page <Access-Space>` and you will see all your spaces and those
```

2020-08-24 15:48 UTC, hghorbel commented
@plamarque  suggestions committed

2020-08-24 15:54 UTC, plamarque requested changes
one wiki occurrence was missed

2020-08-24 15:54 UTC, plamarque commented on docs/Manage-Space.rst
> +   -  Predefined Apps : Home, Documents, Tasks, Forum, Wiki, Calendar, Members, Settings
```suggestion
   -  Predefined Apps : Home, Documents, Tasks, Forum, Notes, Calendar, Members, Settings
```

2020-08-24 15:59 UTC, hghorbel commented
Changes committed @plamarque

2020-08-25 07:55 UTC, plamarque requested changes
more language enhancements missed in previous reviews.

2020-08-25 07:55 UTC, plamarque commented on docs/Manage-Space.rst
> +Display Requested to join  members
```suggestion
Display Join Requests
```

2020-08-25 07:55 UTC, plamarque commented on docs/Manage-Space.rst
> +Also, you can easily manage these applications display order on the space navigation bar
```suggestion
Also, you can easily change the applications display order 
```

2020-08-25 07:55 UTC, plamarque commented on docs/Manage-Space.rst
> +by selecting choices between: *Move After* or *Move Before*.
```suggestion
with *Move After* or *Move Before*.
```

2020-08-25 07:55 UTC, plamarque commented on docs/Manage-Space.rst
> +Every change is automatically saved and the new applications order is available after a refresh.
```suggestion
All changes are automatically saved and the new order is applied after reloading the page.
```

2020-08-25 07:55 UTC, plamarque commented on docs/Manage-Space.rst
> +      receiving notifications of your former publications on this space
```suggestion
      receiving notifications of your former publications done in this space
```

2020-08-25 07:55 UTC, plamarque commented on docs/Manage-Space.rst
>  If you are a member in the space and not an administrator or creator, in
```suggestion
If you are a member in the space and not an administrator
```

2020-08-25 07:55 UTC, plamarque commented on docs/Manage-Space.rst
> +addition to the previously cited components, a Chat button allowing
```suggestion
you will see a Chat button allowing
```

2020-08-26 12:01 UTC, hghorbel commented
@plamarque  Changes done.

2020-09-28 11:34 UTC, hghorbel commented
ping @plamarque need your approve to merge it.

2020-10-26 09:44 UTC, hghorbel commented
@plamarque ping

2020-10-26 22:51 UTC, plamarque approved these changes

2020-10-28 09:56 UTC, merged