Add OpenId documentation
exoplatform/exo-documentation pull request #257
Opened 2020-08-10 07:52 UTC by rdenarie

2020-08-25 07:45 UTC, plamarque requested changes
typos

2020-08-25 07:45 UTC, plamarque commented on docs/OAuthIntegration.rst
> +    based on OAuth procole.
```suggestion
    based on OAuth protocol.
```

2020-08-25 07:45 UTC, plamarque commented on docs/OAuthIntegration.rst
> +The OpenId configuration will depends about which implementation you use, but the steps
```suggestion
The OpenId configuration depends on which implementation you use, but the steps
```

2020-08-25 07:45 UTC, plamarque commented on docs/OAuthIntegration.rst
> +are quite same as for previous vendors :
```suggestion
are similar :
```

2020-08-25 07:45 UTC, plamarque commented on docs/OAuthIntegration.rst
> +You have to create an appliation, provide Authorized Redirect URI, which is
```suggestion
You have to create an application, provide Authorized Redirect URI, which is
```

2020-08-25 07:45 UTC, plamarque commented on docs/OAuthIntegration.rst
> +Then, you will be able to collect a client ID, and a client secret, that will be needed
```suggestion
Then, you will be able to obtain a client ID, and a client secret from the openID provider
```

2020-08-25 07:45 UTC, plamarque commented on docs/OAuthIntegration.rst
> +to configure exo.
```suggestion

```

2020-08-25 07:45 UTC, plamarque commented on docs/OAuthIntegration.rst
> +Theses urls are implicit in other providers, but as OpenId can be implemented by different ways, we have to provide urls.
```suggestion
Theses urls are implicit in other providers, but as OpenId can be implemented in different ways, we have to provide urls.
```

2020-09-04 18:36 UTC, plamarque approved these changes
LGTM

2021-01-25 09:27 UTC, ahamdi approved these changes

2021-01-25 14:50 UTC, merged