Task-54083 : Add documentation for antibrute force system
exoplatform/exo-documentation pull request #314
Opened 2022-05-03 14:32 UTC by rdenarie

2022-05-04 04:16 UTC, plamarque requested changes
first pass review. check my suggestions.

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +       To configure antibrute force system.
```suggestion
       To configure the mechanim that protects against brute force attacks on password authentication.
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +Anti Brute Force Login Protection
```suggestion
Login Brute Force Attacks Protection
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +To prevent an attack based on bruteforce on login form, eXo Platform have an antibrute force system.
```suggestion
To prevent an attack based on brute force on login/password form, a built-in protection mechanism exists.
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +After few failed logins attempts in a short time, the concerned user account is locked for some minutes.
```suggestion
When multiple failed login attempts occur in a short time, the target user account is temporarily locked for a few minutes.
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +When an account is locked, the user can make a forgot password request. After resetting his password, the account is unlocked
```suggestion
When an account is locked, the user can immediately unlock it by resetting its password through a __forgot password__ request.
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +and the user can login normally.
```suggestion
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +There are two properties to configure this feature. To modify it, you can add it in ``exo.properties``.
```suggestion
Two properties control the brute force attack protection mechanism. To configure it, you can add them in ``exo.properties``.
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +The following property allow to configure the number of attempts before the account is locked. The default value is 5 attempts
```suggestion
The following property determines the number of unsuccessful login attempts before the account is locked. The default value is 5 attempts
```

2022-05-04 04:16 UTC, plamarque commented on docs/Security.rst
> +The following property allow to configure the number of minutes the account is locked. The default value is 10 minutes.
```suggestion
The following property determines how long (in minutes) an account is locked when the protection mechanism is triggered. The default value is 10 minutes.
```

2022-05-04 15:41 UTC, plamarque requested changes
markup typo and minor enhancement suggested.

2022-05-04 15:41 UTC, plamarque commented on docs/Security.rst
> +To prevent an attack based on brute force on login/password form, a built-in protection mechanism exists.
```suggestion
To prevent an attack based on brute force on login/password form, a built-in protection mechanism exists : 
```

2022-05-04 15:41 UTC, plamarque commented on docs/Security.rst
> +When multiple failed login attempts occur in a short time, the target user account is temporarily locked for a few minutes.
```suggestion
when multiple failed login attempts occur in a short time, the target user account is temporarily locked for a few minutes.
```

2022-05-04 15:41 UTC, plamarque commented on docs/Security.rst
> +When an account is locked, the user can immediately unlock it by resetting its password through a __forgot password__ request.
```suggestion
When an account is locked, the user can immediately unlock it by resetting its password through a **forgot password** request.
```

2022-06-10 11:41 UTC, rdenarie commented
@plamarque can you revalidate this pr ?
Thanks

2022-06-15 10:52 UTC, plamarque approved these changes

2022-06-15 11:44 UTC, merged