Fix/doc 4253
exoplatform/exo-documentation pull request #51
Opened 2019-02-12 14:42 UTC by mzorai

2019-02-12 14:53 UTC, mzorai commented
Content of this PR could be viewed through this link: https://docs-preprod.exoplatform.org/en/preproduction/Configuration.html#secure-access-to-webdav-urls-of-jcr-folders

2019-02-12 15:08 UTC, ahamdi requested changes
Could you check that we are speaking about allowing the listing of the contents for predefined URLs

2019-02-12 15:08 UTC, ahamdi commented on docs/Configuration.rst
> +    -  :ref:`Secure access to WebDAV urls of JCR folders <Configuration.SecureAccessWebdavJCR>`
I prefer the following title : 
```suggestion
    -  :ref:`Secure the listing of the contents of JCR folders through Webdav <Configuration.SecureAccessWebdavJCR>`
```

2019-02-12 15:08 UTC, ahamdi commented on docs/Configuration.rst
> +       How to secure the access to WebDAV urls of JCR folders.
```suggestion
       How to secure the listing of the contents of folders through Webdav URLs.
```

2019-02-13 16:02 UTC, ahamdi requested changes
Some more comments :)

2019-02-13 16:02 UTC, ahamdi commented on docs/Configuration.rst
> +in eXo Platform allowing to define the set of WebDAV urls to JCR folders
```suggestion
in eXo Platform allowing listing the contents of JCR folders when they are accessed with Webdav 
```

2019-02-13 16:02 UTC, ahamdi commented on docs/Configuration.rst
> +This parameter defines a regular expression of the allowed WebDav urls
```suggestion
This parameter defines a regular expression for the folders that could be listed  
```

2019-02-13 16:02 UTC, ahamdi commented on docs/Configuration.rst
> +to be listed.
to be removed

2019-02-13 16:02 UTC, ahamdi commented on docs/Configuration.rst
> +of JCR folders:
to be removed

2019-02-13 16:02 UTC, ahamdi commented on docs/Configuration.rst
> +          should have this form: **wokspace_Name:/regex**.
```suggestion
          should respect this pattern : **wokspace_Name:/regex**.
```

2019-02-13 16:02 UTC, ahamdi commented on docs/Configuration.rst
> +which means that **the access is allowed to all resources**.
```suggestion
which means that **the contents of All JCR folders are listed**.
```

2019-02-13 16:30 UTC, ahamdi requested changes

2019-02-13 16:30 UTC, ahamdi commented on docs/Configuration.rst
> +to be listed.
```suggestion

```

2019-02-13 16:30 UTC, ahamdi commented on docs/Configuration.rst
> +of JCR folders:
```suggestion
```

2019-02-13 16:37 UTC, mzorai commented on docs/Configuration.rst
> +of JCR folders:
i changed the sentence

2019-02-13 16:42 UTC, ahamdi approved these changes
LGTM

2019-02-13 16:45 UTC, merged