Fix/doc 4288
exoplatform/exo-documentation pull request #99
Opened 2019-06-25 15:05 UTC by hghorbel

2019-06-25 17:47 UTC, plamarque requested changes

2019-06-25 17:47 UTC, plamarque commented on docs/Manage-Space.rst
> +.. note:: Template, Visbility and registration fields have a description of the choice selected to help you taking right decisions when creating a new space.
```suggestion
.. note:: Template, Visibility and registration fields have a description of the choice selected to help you choosing the best template for your needs when creating a new space.
```

2019-06-26 08:52 UTC, mzorai requested changes

2019-06-26 08:52 UTC, mzorai commented on docs/Administration.rst
> +          To display the banner, you can simply click on the eye icon so that the banner will be displayed, and you can click outside the banner or on ESC to close it.
```suggestion
          To display the banner, simply click on the eye icon. To close it, click outside the banner or on ESC button of the keyboard.
```

2019-06-26 09:00 UTC, mzorai approved these changes
LGTM

2019-06-27 08:52 UTC, plamarque commented on docs/Manage-Space.rst
> +.. note:: Template, Visbility and registration fields have a description of the choice selected to help you taking right decisions when creating a new space.
```suggestion
.. note:: Template, Visibility and Registration fields have a description of the choice selected to help you taking right decisions when creating a new space.
```

2019-06-27 08:53 UTC, plamarque requested changes
typo and a comment about the name of the fiels that don't match the screenshot.

2019-06-27 08:53 UTC, plamarque commented on docs/Manage-Space.rst
> +.. note:: Template, Visbility and registration fields have a description of the choice selected to help you taking right decisions when creating a new space.
Also, shouldn't fields be named as they appear on the screenshot to avoid confusion ?

2019-06-27 10:37 UTC, hghorbel commented
@plamarque  need your review (ie approve if all is OK)

2019-06-27 14:33 UTC, plamarque approved these changes
LGTM

2019-06-27 14:44 UTC, merged